// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFBudgetPlanerare.Data;

#nullable disable

namespace WPFBudgetPlanerare.Migrations
{
    [DbContext(typeof(BudgetDbContext))]
    [Migration("20260115105140_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WPFBudgetPlanerare.Models.TransactionBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int?>("RecurringMonth")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasDiscriminator().HasValue("TransactionBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WPFBudgetPlanerare.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWorkHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WPFBudgetPlanerare.Models.Expense", b =>
                {
                    b.HasBaseType("WPFBudgetPlanerare.Models.TransactionBase");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.ToTable("Transactions", t =>
                        {
                            t.Property("Category")
                                .HasColumnName("Expense_Category");
                        });

                    b.HasDiscriminator().HasValue("Expense");
                });

            modelBuilder.Entity("WPFBudgetPlanerare.Models.Income", b =>
                {
                    b.HasBaseType("WPFBudgetPlanerare.Models.TransactionBase");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Income");
                });

            modelBuilder.Entity("WPFBudgetPlanerare.Models.TransactionBase", b =>
                {
                    b.HasOne("WPFBudgetPlanerare.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WPFBudgetPlanerare.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
